apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
    spec:
      containers:
        - name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
          image: gcr.io/ipc-containerdays/{{ .Chart.Name }}:{{ .Values.image.tag }}
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: showks-config
                  key: domain
            - name: AGGREGATOR_URL
              value: http://aggregator$(DOMAIN)
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP
